version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_prod
    image: symfony_app
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - .:/app
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
