# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twilio:
        phone_number: '%env(TWILIO_PHONE_NUMBER)%'
        account_sid: '%env(TWILIO_ACCOUNT_SID)%'
        auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    telegram:
        telegram_url: '%env(TELEGRAM_URL)%'
        telegram_token: '%env(TELEGRAM_TOKEN)%'
    sms_vonage:
        key: '%env(SMS_KEY)%'
        secret: '%env(SMS_SECRET)%'
        organization: '%env(SMS_ORGANIZATION)%'
    multiple_send:
        enabled: '%env(MULTIPLE_SEND)%'
        config:
            sms: '%env(MULTIPLE_SEND_SMS)%'
            email: '%env(MULTIPLE_SEND_EMAIL)%'
            telegram: '%env(MULTIPLE_SEND_TELEGRAM)%'
    cache_settings:
        ttl: '%env(CACHE_TTL)%'
        max_attempts: '%env(MAX_ATTEMPTS)%'

imports:
    - { resource: 'channels/channels.yaml' }

services:
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Symfony\Component\Cache\Adapter\FilesystemAdapter:
        public: true
        arguments:
            $namespace: 'my_cache_namespace'
            $defaultLifetime: 3600
            $directory: '%kernel.cache_dir%/cache'
    
    
    
    App\Entity\User:
        public: true
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    
    # Define the EmailProvider service    
    App\Providers\EmailProvider:
        tags: [ 'app.provider' ]
        public: true
    # Define the TelegramProvider service        
    App\Providers\TelegramProvider:
        tags: ['app.provider']
        public: true

        arguments:
            $config: '%telegram%'

    # Define the Twilio service
    App\Providers\Twilio:
        tags: ['app.provider']
        public: true
        arguments:
            $config: '%twilio%'
    
    App\Providers\Vonage:
        public: true
        arguments:
            $config: '%sms_vonage%'
    
    App\Services\ProviderService:
        arguments:
            $channels: '%channels%'
            $serviceContainer: '@service_container'
            $multipleSend: '%multiple_send%'
            $cache: '@Symfony\Component\Cache\Adapter\FilesystemAdapter'
            $cacheSettings: '%cache_settings%'
            
